### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by LunNova** [ChristophHaag/vkdisplayinfo#1]
Noticed this repo has no license file while packaging it for nixpkgs (https://github.com/NixOS/nixpkgs/pull/173947) so it won't be included in binary caches. At least it's small and builds fast.

Letting you know in case this wasn't intended.

**Comment by ChristophHaag** [comment]
Right, when pushing out a few simple lines of code I often don't think about licensing it. I put the boost license there, same as monado.

If anyone wants to use any of the code under a different license, just let me know.
